modLoader = "kotlinforforge"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "cobblemon_training"
version = "${version}"
displayName = "Cobblemon Training"
authors = "Callum Birks"
description = '''
IV train Cobblemon Pokemon using Bottlecaps!
'''
logoFile = "assets/cobblemon_training/icon.png"

[[dependencies.cobblemon_training]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_training]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_training]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_training]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cobblemon_training]]
modId = "cobblemon"
mandatory = true
versionRange = "1.5.2+1.20.1"
ordering = "AFTER"
side = "BOTH"